services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3:4566
      - HOSTNAME=localstack
    ports:
      - "4566:4566"
      - "4572:4572"
    volumes:
      - "./s3-data:/data"
  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    volumes:
      - ./s3-data:/data
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    entrypoint: /bin/sh -c
    command: >
      -c "
      sleep 5 &&
      aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket my-local-bucket &&
      aws --endpoint-url=http://localstack:4566 s3 cp /data/document1.txt s3://my-local-bucket/document1.txt &&
      aws --endpoint-url=http://localstack:4566 s3 cp /data/document2.txt s3://my-local-bucket/document2.txt
      "
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: document_analyzer_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/init-db:/docker-entrypoint-initdb.d/