/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gustavo.docanalyzer.api;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;


@SpringBootApplication(scanBasePackages = "com.gustavo")
@EnableJpaRepositories(basePackages = "com.gustavo.docanalyzer.infrastructure.db.repository")
@EntityScan(basePackages = "com.gustavo.docanalyzer.infrastructure.db.entity")
public class DocumentAnalyzerApplication {
    public static void main(String[] args) {
        SpringApplication.run(DocumentAnalyzerApplication.class, args);
    }
}
