openapi: 3.0.1
info:
  title: Document Analyzer API
  description: A Spring Boot API for document tracking and analysis.
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Users
    description: Endpoints related to user management and tracking
  - name: Documents
    description: Endpoints related to document analysis
  - name: AI
    description: Endpoints related to AI-powered operations

paths:
  /users/no-upload:
    get:
      tags:
        - Users
      summary: Get users who registered but did not upload documents in a given time period
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            format: date
          required: true
          description: The start date for the period (yyyy-mm-dd)
        - in: query
          name: endDate
          schema:
            type: string
            format: date
          required: true
          description: The end date for the period (yyyy-mm-dd)
      responses:
        200:
          description: List of users who did not upload a document in the specified period
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersNoUploadResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponse'

  /documents/{documentId}/word-frequency:
    get:
      tags:
        - Documents
      summary: Get word frequency for a specific document
      parameters:
        - in: path
          name: documentId
          schema:
            type: string
          required: true
          description: ID of the document
      responses:
        200:
          description: List of words and their frequencies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WordFrequencyResponse'
        404:
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponse'

  /ai/synonyms/longest-word:
    post:
      tags:
        - AI
      summary: Get synonyms for the longest word in a document using Google Gemini Gen AI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                documentId:
                  type: string
                  description: ID of the document
      responses:
        200:
          description: List of synonyms for the longest word
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SynonymsResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponse'

components:
  schemas:
    UsersNoUploadListResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/UsersNoUploadResponse'

    UsersNoUploadResponse:
          type: object
          properties:
            email:
              type: string
              description: User's email address
            registrationDate:
              type: string
              format: date-time
              description: Date the user was registered

    WordFrequencyListResponse:
      type: object
      properties:
        frequencies:
          type: array
          items:
            $ref: '#/components/schemas/WordFrequencyResponse'

    WordFrequencyResponse:
      type: object
      properties:
        word:
          type: string
          description: Word in the document
        frequency:
          type: integer
          description: Number of occurrences of the word

    SynonymsListResponse:
      type: object
      properties:
        synonyms:
          type: array
          items:
            $ref: '#/components/schemas/SynonymsResponse'

    SynonymsResponse:
      type: object
      properties:
        word:
          type: string
          description: Synonym for the longest word


    InternalServerErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
        statusCode:
          type: integer
          description: HTTP status code

    NotFoundErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
        statusCode:
          type: integer
          description: HTTP status code
